version: "3.1"

services:
    backend:
        restart: always
        build:
            context: .
            dockerfile: ./docker-files/Dockerfile.local
        container_name: backend
        image: backend
        ports:
            - "5000:5000"
        volumes:
            - ./:/app
        tty:
            true
        networks:
            - local_net

networks:
    local_net:
        external: false
